# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LHC_Sampling_Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameters', models.TextField()),
                ('numberOfSamples', models.FloatField()),
                ('minimumValues', models.CharField(max_length=100)),
                ('maximumValues', models.CharField(max_length=100)),
                ('algorithm', models.CharField(choices=[('normal', 'normal'), ('optimal', 'optimal')], default='normal', max_length=9)),
            ],
        ),
    ]
